
modera_mjr_integration:
    resource: "@ModeraMjrIntegrationBundle/Controller/"
    type:     annotation
    prefix:   /backend

mf_font_awesome:
    path:      /font-awesome.js
    defaults:  { _controller: ModeraMjrIntegrationBundle:Index:fontAwesome }