
modera_security_aware_js_runtime:
    resource: "@ModeraSecurityAwareJSRuntimeBundle/Controller/"
    type:     annotation
    prefix:   /backend

modera_security_aware_js_runtime.index.application:
    path:      /%mf.jsruntimeintegration.config.app_name%/Application.js
    defaults:  { _controller: ModeraSecurityAwareJSRuntimeBundle:Index:application }